name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v2 

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2 
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Checkout to Application Directory 
        working-directory: /var/www/html/react_nms
      
      - name: Install Node.js dependencies
        run: |
          cd /var/www/html/react_nms 
          npm ci
          
      - name: Build the application
        run: |
          cd /var/www/html/react_nms 
          npm run build
          
      - name: Start the application
        run: |
          cd /var/www/html/react_nms 
          npm start
