name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Start the application with PM2
        run: |
          cd /var/www/html/src
          pm2 start App.js
          
      # Additional steps for running tests, etc.

      - name: Stop the application with PM2
        run: |
          cd /var/www/html/src
          pm2 stop App.js
